#! /bin/bash

# first rsync from jukebox your dicoms to data/dicom folder, then edit globals.sh with paths
#     first make sure the data directory is made with a dicom folder in it
#     for example: rsync -aP /jukebox/dicom/conquest/Prisma-MSTZ400D/NormaL/2024/001_ses04_rtmindeye-1101-1256 /jukebox/norman/rsiyer/rtmindeye/data_ses-04/dicom
# once synced, example usage: ./step1_preproc.sh 001 02 001_ses02_rtmindeye-0813-0955

# LOAD IN GLOBAL VARIABLES
source globals.sh   
module load fsl

# inputs:
subj=$1
session=$2
subj_dir=$3

# convert dicoms to BIDS
echo "converting to BIDS with heudiconv"
$scripts_dir/run_heudiconv.py $subj_dir $subj $session $data_dir

# remove extra stuff generated by heudiconv
rm -rf $bids_dir/sourcedata
rm -rf $bids_dir/.heudiconv

# deface T1w image
mkdir -p $bids_dir/derivatives
mkdir -p $bids_dir/derivatives/deface
echo "Running PYDEFACE on subject $subj, session $session"
$scripts_dir/deface.sh $subj $session

echo "STEP 1 PREPROC COMPLETE"

# now run step2_preproc.sh
# and then finally run run_fmriprep.sh